config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks/create", to: "tasks#create"
  post "tasks", to: "tasks#create"

  get "tasks/new", to: "tasks#new"
  get 'tasks', to: 'tasks#index'
  get "tasks/:id", to: "tasks#show", as: "task"

  get "tasks/:id/edit", to: "tasks#edit", as: "tasks_edit"
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: "tasks_destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.update(params[:id], task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<div class="container">
<h1> New Task </h1>
  <%= form_for(@task) do |f| %>
    <ul>
      <li> <%= f.label :title %> </li>
      <li> <%= f.text_field :title %> </li>

      <li> <%= f.label :details %> </li>
      <li> <%= f.text_field :details %> </li>
      <br>
      <li> <%= f.submit %> </li>
    </ul>
<% end %>

</div>

app/views/tasks/edit.html.erb
<div class="container">
<h1> Edit @task.title </h1>
  <%= form_for(@task) do |f| %>
    <ul>
      <li> <%= f.label :title %> </li>
      <li> <%= f.text_field :title %> </li>

      <li> <%= f.label :details %> </li>
      <li> <%= f.text_field :details %> </li>
      <br>
      <li> <%= f.label :completed %> </li>
      <li> <%= f.check_box :completed %> </li>

      <li> <%= f.submit %> </li>
    </ul>
<% end %>

</div>

app/views/tasks/index.html.erb
<div class="container">
<h1> My Tasks </h1>

<ul>
  <% @tasks.each do |task| %>
  <% if task[:completed] == true %>
    <li> <i class="far fa-check-square"></i>
    <%= link_to task[:title], task_path(task.id) %>  </li>
    <% else %>
    <li>   <i class="far fa-square"></i> <%= link_to task[:title], task_path(task.id) %> -
    <%=  link_to '<i class="fas fa-trash-alt"></i>'.html_safe, task_path(task.id),
      method: :delete,
      data: { confirm: "Are you sure?" }
      %></li>
    <% end %>
  <% end %>
</ul>

  <ul> <%= link_to "Add a new task", tasks_new_path %> </ul>

</div>

app/views/tasks/new.html.erb
<div class="container">
<h1> New Task </h1>
  <%= form_for(@task) do |f| %>
    <ul>
      <li> <%= f.label :title %> </li>
      <li> <%= f.text_field :title %> </li>

      <li> <%= f.label :details %> </li>
      <li> <%= f.text_field :details %> </li>
      <br>
      <li> <%= f.submit %> </li>
    </ul>
<% end %>

</div>

app/views/tasks/show.html.erb
<div class="container">
<h1> <%= @task[:title]  %></h1>

<div class="container background-red">
    <%= @task[:details] %>
    </div>
    <div class="container">
      <% if @task[:completed] == true %>
         <i class="far fa-check-square"></i> The task is completed
      <% else %>
        <i class="far fa-square"></i> The task is not completed yet
      <% end %>
    </div>
      <%= link_to "Back to list", tasks_path %>
      <%= link_to "Edit", tasks_edit_path %>

</div>